---
- hosts: all
  environment: "{{ proxy_env }}"
  become: True
  
  pre_tasks:
    - name: hostnamectl set-hostname
      shell: hostnamectl set-hostname {{ inventory_hostname }}
      when: inventory_hostname is defined
  
  roles:
    - singleplatform-eng.users
    - tomereli.proxy
    - tomereli.oh_my_zsh_p10k
    - geerlingguy.docker
    - andrewrothstein.go
  
  post_tasks:
    - name: add go to path (~/.zshrc)
      lineinfile:
        path: ~/.zshrc
        line: path+=~/go/bin
      with_items: '{{users}}'
      become: yes
      become_user: '{{item.username}}'
      when: users is defined